# ----
# Site

title: Decentraland
url: "https://docs.decentraland.org"
baseurl: ""
#google_analytics_key: UA-63691338-8
disqus_shortname:
newsletter_action:
segment_write_key: ZHLrnVct1IQCx7yLeOzxSic7G1Duy0HH
rollbar_access_token: 28d1884e488447e3a7e7adfd2c4c9375

twitter_url: "https://twitter.com/decentraland"
discord_url: "https://dcl.gg/discord"
github_url: "https://github.com/decentraland"
sdk_url: "https://docs.decentraland.org/"
reddit_url: "https://reddit.com/r/decentraland"
fb_url: "https://www.facebook.com/decentraland/"
faq_url: "https://decentraland.org/#faqs"
telegram_url: "https://t.me/decentralandTG"
legal_url: "https://decentraland.org/legal"
press_url: "https://decentraland.org/press"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/favicon.png
description: Decentraland Documentation
author:
  name: Decentraland
  email: hello@decentraland.org
  twitter: decentraland
social:
  name: Decentraland Documentation
  links:
    - https://github.com/decentraland/documentation

markdown: kramdown

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: "light-theme"
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-target-blank

whitelist:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor

collections:
  sets:

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/images/favicon.png"
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "sets"
    values:
      _hide_content: true
  - scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Github
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
